apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: observability-ingress
  namespace: observability
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /loki(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: loki
            port:
              number: 3100
      - path: /tempo(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: tempo
            port:
              number: 4318
